name: Deploy

on:
  push:
    branches:
      - Test

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to production
        run: |
          echo "Your deployment script here"

      - name: Notify Rollbar
        env:
          ROLLBAR_TOKEN: ec6a917ab74d4c3ea147df80e86888643a286203b84ba5e17ccd855d241c69e58cc6b794a05e09d4b5a2c185a33ba51b
        run: |
          curl https://api.rollbar.com/api/1/deploy/ \
            -F access_token=$ROLLBAR_TOKEN \
            -F environment=production \
            -F revision=${{ github.sha }} \
            -F local_username=${{ github.actor }} \
            -F rollbar_username=${{ github.actor }}

